import React, { useEffect, useRef, useState } from 'react';
import { Alert, Dimensions, Platform, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import GameCard from '../components/cards/GameCard';
import GlassButton from '../components/ui/GlassButton';
import { canPlayCard } from '../game/gameEngine';
import { finishGame, useLocalGameStore } from '../store/localGameStore';
import { gameColors } from '../theme/gameTheme';

export default function GameScreen({ navigation }: any) {
  const { game, draw, pass, play, opponentTurn, settings } = useLocalGameStore(); const [selected, setSelected] = useState<string | null>(null); const finished = useRef(false); const compact = Dimensions.get('window').height < 720;
  useEffect(() => { if (game?.phase === 'opponentTurn') { const timer = setTimeout(opponentTurn, 850); return () => clearTimeout(timer); } if ((game?.phase === 'gameWon' || game?.phase === 'gameLost') && !finished.current) { finished.current = true; finishGame(game.phase === 'gameWon', game.score); navigation.replace('GameOver', { won: game.phase === 'gameWon', score: game.score }); } }, [game?.phase, opponentTurn, navigation, game?.score]);
  if (!game) return null; const top = game.discard[game.discard.length - 1]; const busy = game.phase !== 'playerTurn'; const feedbackEnabled = settings.haptics && Platform.OS !== 'web'; const choose = (id: string) => { const card = game.playerHand.find((item) => item.id === id); if (!card) return; if (!canPlayCard(card, top)) { if (feedbackEnabled) Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error); Alert.alert('Not a match', 'Choose a card with the same suit or rank.'); return; } if (feedbackEnabled) Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); setSelected(id); play(id); setSelected(null); };
  const drawAction = () => { if (feedbackEnabled) Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); draw(); }; const passAction = () => { if (feedbackEnabled) Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); pass(); };
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.eyebrow}>CLASSIC MODE · TURN {game.turnNumber}</Text><Text style={styles.title}>GET WAY</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{game.score}</Text><Text style={styles.scoreLabel}>SCORE</Text></View></View><View style={[styles.opponent, compact && styles.compactOpponent]}><Text style={styles.caption}>OPPONENT</Text><View style={styles.backRow}>{game.opponentHand.slice(0, 5).map((card) => <GameCard key={card.id} faceDown disabled />)}</View><Text style={styles.count}>{game.opponentHand.length} cards remaining</Text></View><View style={styles.table}><View style={styles.pile}><Text style={styles.caption}>DISCARD</Text><GameCard card={top} disabled /></View><View style={styles.pile}><Text style={styles.caption}>DRAW PILE</Text><GameCard faceDown disabled /></View></View><Text style={[styles.action, game.lastAction.includes('does not') && styles.error]}>{game.lastAction}</Text><View style={styles.handArea}><View style={styles.handHeader}><Text style={styles.caption}>YOUR HAND · {game.playerHand.length}</Text><Text style={styles.hint}>{busy ? 'OPPONENT THINKING' : game.hasDrawn ? 'PLAY OR PASS' : 'TAP TO PLAY'}</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.hand}>{game.playerHand.map((card) => <GameCard key={card.id} card={card} selected={selected === card.id} disabled={busy} onPress={() => choose(card.id)} />)}</ScrollView></View><View style={styles.footer}>{game.hasDrawn ? <GlassButton title="PASS TURN" onPress={passAction} disabled={busy} style={styles.draw} /> : <GlassButton title="DRAW CARD" onPress={drawAction} disabled={busy} style={styles.draw} />}<GlassButton title="QUIT" onPress={() => navigation.goBack()} style={styles.quit} /></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: gameColors.felt, padding: 18 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: gameColors.aqua, fontSize: 10, letterSpacing: 2, fontWeight: '900' }, title: { color: gameColors.cloud, fontSize: 30, fontWeight: '900', marginTop: 5 }, score: { alignItems: 'flex-end' }, scoreValue: { color: gameColors.gold, fontSize: 30, fontWeight: '900' }, scoreLabel: { color: gameColors.muted, fontSize: 10, letterSpacing: 1 }, caption: { color: gameColors.muted, fontSize: 10, letterSpacing: 1, fontWeight: '900' }, opponent: { alignItems: 'center', marginTop: 26 }, compactOpponent: { marginTop: 12 }, backRow: { flexDirection: 'row', marginTop: 10 }, count: { color: gameColors.muted, fontSize: 12, marginTop: 8 }, table: { flex: 1, minHeight: 150, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 22 }, pile: { alignItems: 'center', gap: 10 }, action: { color: gameColors.cloud, textAlign: 'center', fontSize: 14, minHeight: 40, paddingHorizontal: 10 }, error: { color: gameColors.coral }, handArea: { marginTop: 10 }, handHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, hint: { color: gameColors.gold, fontSize: 10, fontWeight: '900' }, hand: { paddingVertical: 22, paddingHorizontal: 4, alignItems: 'flex-end' }, footer: { flexDirection: 'row', gap: 10 }, draw: { flex: 1, backgroundColor: gameColors.gold, borderColor: gameColors.gold }, quit: { paddingHorizontal: 20, backgroundColor: 'transparent', borderColor: gameColors.line } });