services:
  - type: web
    name: bhabhi-thulla-server
    env: node
    buildCommand: npm install ; npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
